### ISSUE TITLE
jump-to-definition inside the editor for java symbols

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#181]
Original [issue 140](https://code.google.com/p/counterclockwise/issues/detail?id=140) created by laurentpetit on 2010-09-03T22:06:35.000Z:

class names symbols
static class field symbols
static method field symbols

**Comment by avli** [comment]
@laurentpetit Am I correct, and this issue means ccw cannot jump to Java code definitions and it's not my environment bug? Thanks in advance.

**Comment by laurentpetit** [comment]
indeed
