### ISSUE TITLE
Double-click word with dash should select full word

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#516]
Original [issue 475](https://code.google.com/p/counterclockwise/issues/detail?id=475) created by laurentpetit on 2012-11-20T01:19:30.000Z:

I often want to select a function or variable name in the editor to search for all instances of it in the code base, but the editor will not select past a &quot;-&quot; character. Since the dash is the standard way to separate words in clojure, this makes it difficult to select these names in CCW.

**Comment by laurentpetit** [comment]
@arichiardi you might be interested in studying how I implemented double-click. Especially in relation to paredit usage.

**Comment by arichiardi** [comment]
I will! :wink:
