### ISSUE TITLE
ANSI-compatible REPL output

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#665]
Original [issue 624](https://code.google.com/p/counterclockwise/issues/detail?id=624) created by laurentpetit on 2014-03-27T14:00:09.000Z:

from fmjrey:
Aptana Studio 3 has a nice built-in terminal, which acts exactly as a console with proper VT100/ANSI code display. 
However I think proper rendering could easily be implemented in CCW by using the same hack used by AnsiConsole:
https://github.com/mihnita/ansi-econsole/blob/master/AnsiConsole/src/mnita/ansiconsole/participants/AnsiConsolePageParticipant.java
In other words you probably just need to define a listener similar to AnsiConsoleStyleListener and add it to your StyledText widget in ccw.repl.REPLView:
REPLStyleListener myListener = new REPLStyleListener();
viewerWidget.addLineStyleListener(myListener);

need from Mark Engelberg:
On a related note, the same blog post describes a library for pretty-printing stacktraces:
https://github.com/AvisoNovate/pretty
I'm curious to try it, but the color codes it uses seem to generate garbage in the REPL.  Is there some setting that will make this work?

I guess it's targetting textual consoles, and maybe even more specifically Linux/Unix textual consoles ?

Don't know the library, must take the time to play with it.

**Comment by arichiardi** [comment]
Is this good? I guess we have everything in place..

**Comment by laurentpetit** [comment]
It's working when one installs the relevant plugin, right?

- should we start to embed the ansi color plugin with CCW, and also the plugin ?
- should we just reference the plugin, and let users use it ?

**Comment by arichiardi** [comment]
I use it all the time together with venatius/ultra in my profile.clj. For me it makes sense to have both included...but I did not mind the extra work...it was easy to deploy...it is hard to say...maybe we can waitk for a user explicit request before embedding..

**Comment by laurentpetit** [comment]
What is venatius/ultra ?

**Comment by laurentpetit** [comment]
ok, found, and indeed it's useful ! Working on embedding ansi stuff with CCW

**Comment by arichiardi** [comment]
Yes it's great and displays well in ccw with ansi...sorry I do not have stable connection today and I could not immediately link the repo

**Comment by laurentpetit** [comment]
found the repo

2015-07-22 13:48 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Yes it's great and displays well in ccw with ansi...sorry I do not have
> stable connection today and I could not immediately link the repo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/665#issuecomment-123688782>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
ok, done, user plugin embedded, ans ansi econsole plugin packaged with the standalone ccw

**Comment by arichiardi** [comment]
:+1:
