### ISSUE TITLE
REPL only visible in perspective where it was open

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#686]
Original [issue 645](https://code.google.com/p/counterclockwise/issues/detail?id=645) created by laurentpetit on 2014-07-17T14:50:43.000Z:

Should be visible in more perspectives by default (Java, Debug, PDE, etc.)

**Comment by alins** [comment]
i get this is getting worked on for the next milestone ?

**Comment by laurentpetit** [comment]
Hello. The `next` Label is for Issues that have high probability of being included in a next iteration, but not the one that we are currently working on. So yes, for the next milestone, but not the release to come next.

**Comment by laurentpetit** [comment]
Since the next release is waiting for `cider-nrepl` to stabilize, there is some room for adding `easy to fix` issues in the mean time. I will set this one so it is considered.

**Comment by laurentpetit** [comment]
See this for inspiration: http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fworkbench_perspectives.htm

**Comment by laurentpetit** [comment]
OK, so we'll have to listen to perspective deactivation / activation events, or something like that, so that we dynamically add REPL Views to the Debug Perspective.

**Comment by arichiardi** [comment]
:+1: cool!
