### ISSUE TITLE
Bind key to (doc ...) and tooltip display in Editor.

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#688]
Original [issue 647](https://code.google.com/p/counterclockwise/issues/detail?id=647) created by laurentpetit on 2014-07-18T11:19:49.000Z:

I am very happy with Counterclockwise in general and the doc feature in particular.
When I hover on a symbol, it perfectly shows the documentation as per (doc XXX) evaluation in repl.

What I cannot do is to associate a key to it. Usually the tool-tip shows with a comfortable F2. I don't know if it is a CCW problem or an Eclipse problem.
I apologize if it is the latter.

I currently use Eclipse Luna and CCW as plugin.

**Comment by arichiardi** [comment]
BTW  [this](https://github.com/arichiardi/ccw/commit/1a80a11f57102d594ac877f694f4a0eb7035384b) commit solves this  problem

**Comment by arichiardi** [comment]
Closing as it is solved.
