### ISSUE TITLE
Failures out of memory and lockups with 0.28.1

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#699]
Original [issue 658](https://code.google.com/p/counterclockwise/issues/detail?id=658) created by laurentpetit on 2014-09-29T07:27:54.000Z:

I currently use Eclipse as a ClojureScript editor and build outside eclipse. I have a large workspace with very many projects many just so I can view the source in eclipse.

I have some major problems with 28.0 28.1, it is trying to update the project files but has many failures including out of memory, I can't stop the update attempt. I have had to force quit Eclipse several times and lost my workbench state.

I think the auto project update needs to be optional.

**Comment by arichiardi** [comment]
BTW this commit solves [this](https://github.com/arichiardi/ccw/commit/1a80a11f57102d594ac877f694f4a0eb7035384b) problem
