### ISSUE TITLE
Update leiningen dependencies should not block the workspace that long ...

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#712]
Original [issue 671](https://code.google.com/p/counterclockwise/issues/detail?id=671) created by laurentpetit on 2014-11-20T21:15:27.000Z:

the big maven download should occur outside the job

It's bad when the user cannot save their work because a background upgrade occurs ...

**Comment by arichiardi** [comment]
I have just noticed that this one is still not ok. Update Dependencies blocs the UI and does not have any progress displayed. I think we should reopen it, maybe it is a regression.

**Comment by laurentpetit** [comment]
You're right, I have also noticed that it's still not optimal. Reopening it.

**Comment by laurentpetit** [comment]
A rather radical move to fix both issues at once (progress displayed and no blocked UI) could be to stop trying to use leiningen as embedded, but rather start it as an external java process (via the leiningen launch configuration in `ccw.leiningen.launch` namespace & al) => the progress would be written to the console (at least as much as leiningen also lets go through its stdout).

Needs some thinking about the right leiningen command to get the classpath, and also how to parse the result, etc.
Just food for thought.

**Comment by laurentpetit** [comment]
(Suggesting this because this would be a move in the right direction IMHO: getting rid of the embedded Leiningen jar: it's heavyweight - doubles at least counterclockwise plugin's size with all its dependencies-, and a moving target wrt Internal API. We should consider that the right API to talk to Leiningen is the command line arguments.

**Comment by arichiardi** [comment]
Yes, but also a lot of plugins allow the user to choose between the embedded and the "external" version. But I don't know if it makes sense for lein, which is self-installable, self-upgradable..self-contained. You are right, switching to the command line is a good solution, maybe have a dedicated part that can show profiles dependencies and commands as well, a-la-maven plugin. By the way, I wonder if somebody has every written something like it for Leiningen integration in Eclipse.

The final step will then be to have a dedicated Counterclockwise perspective.

**Comment by arichiardi** [comment]
A temporary patch would be to put everything in a [Background Task](http://www.vogella.com/tutorials/EclipseJobs/article.html)

**Comment by laurentpetit** [comment]
That's more or less what I thought had been done. Weird.

**Comment by arichiardi** [comment]
Ah ok, sorry...I did not check the code.

**Comment by laurentpetit** [comment]
I re-tested this issue, and I see none? Everything is already done in jobs, and it's possible to send to the background by clicking on the right button. Can you describe more precisely when the UI hang happens?

**Comment by laurentpetit** [comment]
Oooh, now I see, and you are totally right. I always tested through "Reset Project ...", and there it works well. It's true that "Update Dependencies" is blocking. Good catch!

**Comment by arichiardi** [comment]
Yesterday I added a :plugins entry and right clicked on my project root (on the left) and Lein->Update Dependencies.

**Comment by arichiardi** [comment]
Great exactly there.

**Comment by laurentpetit** [comment]
Argh, still not good. Will work on it again, but later...

**Comment by laurentpetit** [comment]
now it's ok

**Comment by laurentpetit** [comment]
easy to reproduce: temporarily move your `~/.m2/repository/` folder elsewhere, and attempt an `Update project dependencies` on a project with lots of deps. Should not block the UI anymore.

**Comment by arichiardi** [comment]
Now the progress shows up, does it allow cancelling the operation?

**Comment by arichiardi** [comment]
The update itself works!

**Comment by laurentpetit** [comment]
No canceling the operation won't work out of the box but could probably be done with some work

**Comment by laurentpetit** [comment]
I will accept the PR as is. We'll see later for the cancellation, if you don't mind (and we'll open a new ticket)
