### ISSUE TITLE
No code assist in REPL

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#721]
Original [issue 680](https://code.google.com/p/counterclockwise/issues/detail?id=680) created by laurentpetit on 2014-12-05T15:18:13.000Z:

<b>What steps will reproduce the problem?</b>
1. Fire up some project and its REPL
2. Open a paren to write some code
3. Press CTRL-Space

Before version STABLE 31.1, a window with code assist was displayed to the user. At the moment that window does not show up anymore.

**Comment by arichiardi** [comment]
I think this one can be closed.
