### ISSUE TITLE
Unable to open any file with versions >= 0.30

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#723]
Original [issue 683](https://code.google.com/p/counterclockwise/issues/detail?id=683) created by laurentpetit on 2014-12-15T13:00:55.000Z:

<b>What steps will reproduce the problem?</b>
1. Install version 0.30 or newer of the CCW plugin.
2. Open an already imported project.
3. Try to open a .clj file to edit it.

<b>What is the expected output? What do you see instead?</b>

With versions &lt;= 0.29 of the plugin, I can open and edit the files without problems. With versions &gt;= 0.30, in the place of the contents of the file, I get the message: &quot;The editor class could not be instantiated. This usually indicates a missing no-arg constructor or that the editor's class name was mistyped in plugin.xml.&quot;

<b>What version of the product are you using? On what operating system?</b>

I am using Eclipse from Debian's unstable repository (3.8.1) and the CCW plugin.

<b>Please provide any additional information below.</b>

This bug seems to be a regression. I can attach here the stack trace that I get, if needed.

Thanks,

Rogério Brito.

**Comment by arichiardi** [comment]
About this I agree with never having seen anyone installing eclipse from distro's repos. In my experience, Kepler on Ubuntu is a pretty stable developing environment ... I am currently using it to develop ccw (using the latest stable plugin installed from the update manager) and never had issues..
