### ISSUE TITLE
outline disappears if cljx prefixes are used

### ISSUE THREAD

**Issue by ilazarte** [laurentpetit/ccw#733]
cljx is a pretty common pre-parser of forms.  From one .cljx file you can generate a .clj and .cljs file saving a lot of needless file creation and highly promoting reuse.  Currently if you use the prefixes required, you will lose outline (even after cljx has been added as correctly content-type file-type etc in eclipse).

To reproduce simply add a #+clj or #+cljs in front of any form.
https://github.com/lynaghk/cljx

They name ccw as a supporting ide, so I believe this would look good for the community as well as be a courteous thing to support.

**Comment by laurentpetit** [comment]
I wasn't aware that there was a problem with this, thanks for reporting!

**Comment by laurentpetit** [comment]
ok, now the .cljx file extension is recognized. And the outline works again
