### ISSUE TITLE
Leverage cider-nrepl instead of ccw.server if found

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#734]
# Goals of this issue

If `cider-nrepl` ops are available for a session, use these ops instead of `ccw.server`:

* [x] for context info inside forms (when typing `Shift+Alt+Space`)
* [x] for documentation hover over symbols
* [x] basic integration for the editor content assist (list, lateral additional information)
  * [x] correct highlight of found letters in the list
  * [x] correct display of arglists in additional information
* [x] implement the choice of the fn to call (either ccw.server or cider-nrepl)
* [x] reuse the user repl nREPL session-id to enable clojurescript completion
* [x] wait for `cider-nrepl 0.9.0` to become stable, or check that everything works with version `0.8`
* [x] regression-tests with plain `ccw.server` usage
# Non Goals of this issue

* replacing `ccw.server` with `cider-nrepl`. It's too early. We'll just use `cider-nrepl` when available
* automatigally adding `cider-nrepl` as a leiningen dependency as we do for `ccw.server`. The former can cause problems to some user projects (dependency conflicts), while the latter does not have this problem. So we will currently let users choose to enable `cider-nrepl` by having it as a plugin in their leiningen user profile or project plugins lists ( `:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]]`).

**Comment by arichiardi** [comment]
:+1:

**Comment by bbatsov** [comment]
Nice!

**Comment by arichiardi** [comment]
I would add, for hovers as well! Source hover, meta hover, once we integrate my contribution the sky's the limit!

**Comment by laurentpetit** [comment]
I've narrowed down the scope of the issue and created a new bug for introducing more advanced features.

The current one is just waiting to being more battle tested before being merged
