### ISSUE TITLE
Unable to locate java.classpath from refactor-nrepl hidden dependency

### ISSUE THREAD

**Issue by arichiardi** [laurentpetit/ccw#748]
I decided to make it a first class error :D 
Since two/three hours ago, I know it is absurd, every time I try to launch a Repl, this error is shown and the IDE goes to the Debug perspective:

    Error loading refactor-nrepl.middleware: java.io.FileNotFoundException: Could not locate clojure/java/classpath__init.class or clojure/java/classpath.clj on classpath: , compiling:(refactor_nrepl/ns/slam/hound/search.clj:1:1)

    Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)

I do not understand why...I java.classpath it in ccw pom.xml, build.properties. It might be in my conf , because it happens in any branch. I should maybe git bisect, but I tried some old commit, before ```cider-nrepl``` was merged, and I still have the issue. What can it be? here is the command line if it can help to figure out...really really weird...

    Launched process with command line: /usr/lib/jvm/java-8-oracle/bin/java -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:55269 -Dccw.repl.launchid=9d078bd1-99c5-4fae-8a78-a8493597dded -client -Xbootclasspath/a:/home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/leiningen-standalone.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -classpath /home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/leiningen-standalone.jar:/home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/lein clojure.main -m ccw.leiningen.main update-in :jvm-opts concat "[\"-Xdebug\" \"-Xrunjdwp:transport=dt_socket,server=y,suspend=n\"]" -- update-in :dependencies conj "[ccw/ccw.server \"0.1.1\"]" -- update-in :injections conj "(require 'ccw.debug.serverrepl)" -- update-in : dissoc :main -- repl :headless

My testing ```project.clj```:

    (defproject clj-test "0.1.0-SNAPSHOT"
      :description "FIXME: write description"
      :url "http://example.com/FIXME"
      :license {:name "Eclipse Public License"
                :url " !http://www.eclipse.org/legal/epl-v10.html"}
      :dependencies [[org.clojure/clojure "1.6.0"]])

![selection_004](https://cloud.githubusercontent.com/assets/1724788/7237778/0a0f3086-e79e-11e4-985c-ffed5983a8ca.png)

**Comment by arichiardi** [comment]
It might be exactly [this](https://github.com/clojure-emacs/refactor-nrepl/issues/63) issue. Maybe we need to bump ```refactor-nrepl``` to ```1.0.3```. Are we "injecting" the dependencies?

**Comment by arichiardi** [comment]
By the way, ```:plugins [[refactor-nrepl "1.0.3"]]``` in ```project.clj``` solved.

**Comment by laurentpetit** [comment]
Ok, so maybe we just close the issue? Or is there something else to do?
