### ISSUE TITLE
Pretty Print in REPL

### ISSUE THREAD

**Issue by gary-schiltz** [laurentpetit/ccw#752]
It would be nice to have the option of having the output to the REPL be automatically pretty printed. CIDER and nREPL under Emacs has an option to toggle pprint, and it would be nice to have the same functionality in CCW.

**Comment by laurentpetit** [comment]
CCW will ship in the next release with `cider-nrepl` support. Not all `cider-nrepl` ops will be implemented at first, though. It may still be time to consider supporting the `pprint` feature of cider-nrepl before cutting the release.
Placing in the milestone for consideration.

**Comment by laurentpetit** [comment]
`cider-nrepl` does not enable `pprint` by default. Working on it, See #753

**Comment by laurentpetit** [comment]
OK, with the upcoming release, the use of `cider-nrepl` nREPL middlewares for your project will enable the pprint feature
