### ISSUE TITLE
Loading User Plugins should not block the IDE?

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#757]
Currently, loading the user plugins blocks the UI, since it's done in the UI thread, and it can be quite time consuming.

- [x] Check if it is normal that for a handful of user plugins it seems to take so long on my computer
- [x] Consider moving user plugins to a background thread. This will have an important implication:
  - user plugins will not be able anymore to presume they're called from the UI Thread.
  - check that calls to defcommand, defhandler, etc. still work, then

**Comment by laurentpetit** [comment]
Cannot be moved to background thread or there will be conflicts.
Should improve load time of namespace `ccw.core.e4.model` which takes 11 (eleven!) seconds on my laptop. Maybe too macro and reflection heavy?

**Comment by arichiardi** [comment]
By the way, I have noticed that the delay that loads the main embedded repl also freezes the UI. Might be worth changing it to a future.

**Comment by laurentpetit** [comment]
I'll take a look at it
