### ISSUE TITLE
preview cider nrepl integration and cljx

### ISSUE THREAD

**Issue by ilazarte** [laurentpetit/ccw#759]
not sure if this is supposed to work yet, but posting steps to replicate no successful completion.  i have figwheel configured, ultimately i would expect someone would use an autotest to develop using cljx-start-lib template, which is intended to be a starter project for a clj/cljs lib.

i used the standalone distro to run this.

1. create project from cljx-start-lib (a cljx enabled clj/cljs lib)
2. add deps to project.clj (attached at bottom)
3. execute lein once in external console (wait for compilation)
4. execute lein auto in external console (starts cljx->cljs autobuilder)
5. start ccw repl
6. change core.cljx function to following:
    
    (defn foo []
      #+clj
      (str "Happy CLJ hacking!")
      #+cljs
      (str "Happy CLJS hacking!"))

7. eval function and verify cljx clj works in repl (yay).
8. switch to cljs repl via:  (cemerick.piggieback/cljs-repl (cljs.repl.rhino/repl-env))
9. execute (foo) in repl and receive following message:
WARNING: Use of undeclared Var cljs.user/foo at line 1 <cljs repl>

---- project.clj
(defproject learn-cljx-start-lib "0.1.0-SNAPSHOT"

  :description "FIXME: write this!"
  
  :url "http://example.com/FIXME"

  :scm {:name "git"
        :url  "https://github.com/user/learn-cljx-start-lib"}
  
  :license {:name "Eclipse Public License"
            :url  "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-3149"]
                 [hiccup "1.0.5"]
                 [compojure "1.3.2"]
                 [ring "1.3.2"]
                 [ring/ring-json "0.3.1"]
                 [figwheel "0.2.5"]]
  
  :plugins [[com.keminglabs/cljx "0.6.0"]
            [lein-figwheel "0.2.5"]
            [lein-cljsbuild "1.0.5"]
            [lein-pdo "0.1.1"]
            [cider/cider-nrepl "0.9.0-SNAPSHOT"]]

  :jar-exclusions [#"\.cljx|\.svn|\.swp|\.swo|\.DS_Store"]
  
  :source-paths ["src/cljx"] ;add src/clj src/cljs if used
  
  :figwheel {:port 3449}
  
  :cljx {:builds [{:source-paths ["src/cljx"]
                   :output-path "target/classes"
                   :rules :clj}
                  
                  {:source-paths ["src/cljx"]
                   :output-path "target/generated/classes"
                   :rules :cljs}
                  
                  {:source-paths ["dev/cljx"]
                   :output-path "target/classes"
                   :rules :clj}
                  
                  {:source-paths ["dev/cljx"]
                   :output-path "target/generated/classes"
                   :rules :cljs}]}
  
  :cljsbuild {:builds {:learn-cljx-start-lib 
                       {:source-paths ["target/classes" "target/generated/classes"] ;add src/clj src/cljs if used
                        :compiler {:output-to "resources/public/js/learn_cljx_start_lib.js"
                                   :source-map "resources/public/js/learn_cljx_start_lib.js.map"
                                   :output-dir "resources/public/js" 
                                   :optimizations :none}}}}
  
  :profiles {:dev {:source-paths ["dev/cljx"]
                   
                   :dependencies [[com.cemerick/piggieback "0.2.0"]
                                  [org.clojure/tools.nrepl "0.2.10"]]
                   
                   :plugins [[lein-ring "0.9.3"]]
                   
                   :aliases {"once" ["do" "cljx" "once," "cljsbuild" "once"]
                             "auto" ["pdo" "cljx" "auto," "cljsbuild" "auto"]
                             "dev"  ["pdo" "ring" "server-headless" "8080," "cljx" "auto," "figwheel"]}
              
                   :repl-options {:nrepl-middleware
                                   [cemerick.piggieback/wrap-cljs-repl]}
                   
                   :ring {:handler       cljx-start-lib.routes/app
                          :auto-reload?  true
                          :auto-refresh? false}}})

**Comment by laurentpetit** [comment]
Could you share the minimalist project on github. Just having to clone it instead of trying to reproduce the different introductory steps would greatly help the debugging.

**Comment by laurentpetit** [comment]
I'm stuck at point 7:
- When I call `(foo)` in the REPL I get `"Happy hacking!"` and not `"Happy CLJ hacking!"`.
- If I then try to eval the function `foo` from the editor via `Cmd+Enter` I get a compiler runtime exception:

```
RuntimeException No reader function for tag +clj  clojure.lang.LispReader$CtorReader.readTagged (LispReader.java:1180)
RuntimeException No reader function for tag +cljs  clojure.lang.LispReader$CtorReader.readTagged (LispReader.java:1180)
RuntimeException Unmatched delimiter: )  clojure.lang.Util.runtimeException (Util.java:221)
```

**Comment by laurentpetit** [comment]
Please help

**Comment by ilazarte** [comment]
Will take a look asap..

**Comment by laurentpetit** [comment]
Hello, @ilazarte . We're close to releasing CCW `0.32.0`. If it's possible for you to help me qualify this bug, I'll try to work on it for this release, or else I'll be forced to postpone it. Cheers.

**Comment by ilazarte** [comment]
that seems like an unmatched brace error, unless cider simply doesn't understand cljx...  i'm sorry i'm so strapped for time.  I'll try to look into it post release.
