### ISSUE TITLE
Find out why `cider-nrepl` takes so long to initialize from within CCW

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#764]
Taking more than 7 seconds on my laptop, 10x to 40x longer than any other namespace plus their dependencies.

**Comment by laurentpetit** [comment]
Here is a gist with the execution times on my Mac Book Air 2012, 4Gbytes of RAM, SSD, core i5.

https://gist.github.com/laurentpetit/fb86ea923dfb02e673da

The Counterclockwise version tested is launched from a development environment.
Almost no namespace is AOT-compiled but the clojure core ones.

**Comment by laurentpetit** [comment]
First idea that comes to mind: AOT-compile everything in `ccw.core/lib/`. At least to see the difference in load time, which I expect to be huge, because the number of dependencies loaded e.g. for `cider-nrepl` is huuuuuge.

**Comment by arichiardi** [comment]
Wow good job! Are you going to use ```lein``` for all deps during the ```install``` phase?

**Comment by arichiardi** [comment]
I was also inspecting [this](https://github.com/clojure-android/clojure) in order to see what they did to shrink the loading time, but I think it is too specific for the Android platform.

**Comment by arichiardi** [comment]
Another project worth its salt: [Skummet](http://clojure-android.info/skummet)

**Comment by laurentpetit** [comment]
Funny, I also thought about skummet this evening. Worth giving a try I think.

**Comment by laurentpetit** [comment]
I think I will try in order:
- a little bit more tests with the current setup to check that the numbers are stable
- leverage clojure AOT compilation and see what the numbers become
- same with skummet

**Comment by arichiardi** [comment]
:+1:

**Comment by laurentpetit** [comment]
Once everything in `ccw.core/lib/` is AOT compiled (and Clojure has been patched to not initialize classes to early, and `cider-nrepl` has been patched to work AOT, and CCW has been patched as well), the result is:

Time for loading `cider-nrepl` and all its deps takes 1/2 the time without AOT compilation. Interesting result. I would have hoped even more, but that's already a good win.

Next try: `skummet`

**Comment by laurentpetit** [comment]
won't try skummet for now. Will already try to accomplish standard AOT compilation of Clojure.

**Comment by laurentpetit** [comment]
Another interesting idea is to compile and elide metadatas. This may improve performance one step further.

**Comment by arichiardi** [comment]
Oh good steps ahead! Skummet was just an idea as they are trying to accomplish the same I guess, but I guess in this case it is also good to have control..in case skummet is not just a drop-in..I mean

**Comment by laurentpetit** [comment]
Currently I'm banging my head against the walls because I have touched many pieces (recompiled, cider-nrepl, ccw, clojure-ccw) to make AOT work.
Stepping backwards and doing things slowly, one step at a time.

**Comment by arichiardi** [comment]
Yes of course, keep it slow, is the only way to make things work :+1: Just throwing ideas around here :smile:

**Comment by laurentpetit** [comment]
@arichiardi I'd like to make loading `cider-nrepl` handler for CCW internals `off` by default, since it takes up so much more time to load and most users won't benefit from it.

- either I add another property option
- either I tie it to the existing option to autostart the repl when CCW starts (because generally speaking, if one sets the autostart option, then one wants to connect to the repl for all batteries included)

thoughts?

**Comment by arichiardi** [comment]
I'd go for the second, as the internal nrpel is used mostly by devs (I guess).
What about user-handled projects? Did you notice any slow down?

**Comment by arichiardi** [comment]
I mean ..by ccw development

**Comment by laurentpetit** [comment]
Not really. And you?

**Comment by arichiardi** [comment]
No, probably no lovelocks/deadlocks there as everything is already loaded

**Comment by arichiardi** [comment]
Ahah lovelocks is funny, sorry I was on mobile :)

**Comment by laurentpetit** [comment]
PR #767 adds AOT compilation to CCW plugin and CCW/Standalone
