### ISSUE TITLE
Cache strategies in ClojureOSGi

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#772]
2 caches could be used:

- [x] Cache the BundleClassLoader https://github.com/laurentpetit/ccw/blob/7cb8cd999a46a73c69c8ae80946e6987bf256af0/ccw.core/src/java/ccw/util/osgi/ClojureOSGi.java#L65
- [x] Cache the list of already required namespaces to provide a quick exit before even going synchronized (will need to use a synchronized block, or a second synchronized method https://github.com/laurentpetit/ccw/blob/7cb8cd999a46a73c69c8ae80946e6987bf256af0/ccw.core/src/java/ccw/util/osgi/ClojureOSGi.java#L94

**Comment by laurentpetit** [comment]
@arichiardi you expressed the desire to do this, feel free to jump in first

**Comment by arichiardi** [comment]
First thought after skimming (more on this later): at the ```namespace``` level is better, so that we can have finer control.

**Comment by laurentpetit** [comment]
started working on this (thus assigned to me as a reminder)

**Comment by arichiardi** [comment]
OK great today I was checking macro hover and did not have time to start, I will code review it with pleasure :smile:

**Comment by laurentpetit** [comment]
I will merge this one
