### ISSUE TITLE
Cleanup the System Properties to get back to official Clojure

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#778]
Since the fix proposed upstream to Clojure core has been declined (as expected): http://dev.clojure.org/jira/browse/CLJ-1717?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

We need to work around the problem introduced by Equinox.

The suggestion is to cleanup the System properties of their non-String values as soon as possible.

**Comment by laurentpetit** [comment]
We need to do this to be able, sooner or later, to come back to the official clojure version.

**Comment by arichiardi** [comment]
So....meaning all the -D properties are affected?

**Comment by laurentpetit** [comment]
Equinox sets some values of System properties, sneakily, to non-String values. Looking at the Eclipse bug referenced by Alex MIller in CLJ-1717, this is a known issue on the Eclipse side, and while we're not sure all our CCW codebase switched to a version without the defect, we should take care of this ourselves.

Currently it's done in CCW's patched version of Clojure. But we could try to do it on CCW's side by looping over all System properties and replacing by nil or their toString() value all non-String values.

But we must find a way to do it as early as possible, so probably during the ClojureOSGi.initialize() call() which is a guaranteed point of "rendez-vous" for loading clojure code in CCW.

**Comment by arichiardi** [comment]
Oh now I have understood, yep that is probably the best place, and coherent as you said

**Comment by arichiardi** [comment]
Can we embed E4 RCP Patch (bugzillas 445122) ?  It looks like it is working fine in the other bundles..

**Comment by laurentpetit** [comment]
what do you mean by "embedding" ?

**Comment by arichiardi** [comment]
Talking about [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=445122#c51)

**Comment by arichiardi** [comment]
Sorry I was checking the bug on my phone and I might have overlooked something..

**Comment by laurentpetit** [comment]
I think we will just keep the commit in clojure-ccw for a while, and remove
it later, when Mars is released and we're pretty confident that most users
are on Luna SR2 at least.

2015-05-19 14:26 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Sorry I was checking the bug on my phone and I might have overlooked
> something..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/778#issuecomment-103467357>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
OK. Problem mentioned in laurentpetit/clojure-ccw/CCW-CHANGES.md. Closing this issue.
