### ISSUE TITLE
Remove the code for CLJ-1620 when it is merged upstream

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#779]
CLJ-1620 has been accepted, so it will be possible to remove the associated commits in `clojure-ccw`

See http://dev.clojure.org/jira/browse/CLJ-1620?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

**Comment by arichiardi** [comment]
:+1:

**Comment by laurentpetit** [comment]
It has finally been postponed to post 1.7. Closing this issue
