### ISSUE TITLE
Editor completion Regression

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#785]
I noticed that the part which does hippie-completion (totally based on the content of the current file) does not work anymore.

I will investigate a little bit, dunno what caused this. Maybe this could be an interesting time to try adding an automated test for this regression. Will probably be hard, involving content assist and checking the list size, smth like that :-) /cc @arichiardi

**Comment by laurentpetit** [comment]
@arichiardi here is the Exception I get while doing Ctrl+Alt https://gist.github.com/laurentpetit/b00093e4943928c321d8

It seems to happen since I have switched to Eclipse Mars (currently RC1)

**Comment by arichiardi** [comment]
It looks like jdt's problem...at first sight, but will investigate

**Comment by arichiardi** [comment]
Mmm...looks like Jdt's content assist is triggering...

Maybe they added a new shortcut to trigger that my Ctrl-Alt is not overriding..

**Comment by arichiardi** [comment]
@laurentpetit can you explain me how it works briefly? I don't think my hovering is interfering here right? A test is a good idea!

**Comment by laurentpetit** [comment]
it's weird. I started noticing it on my own dev Eclipse when I had
installed a recent ccw from master. Then I didn't notice it again, then I
noticed it after another install. And now there's no problem inside my
launched dev instance.

Will keep this open and indeed try to qualify more.

2015-05-29 8:28 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> @laurentpetit <https://github.com/laurentpetit> can you explain me how it
> works briefly? I don't think my hovering is interfering here right? A test
> is a good idea!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/785#issuecomment-106707066>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
@arichiardi Seems like a bug in JDT, look at this optimistic class cast:
https://github.com/azachar/org.eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaContentAssistHandler.java#L60

**Comment by laurentpetit** [comment]
@arichiardi bug reported to the JDT bugtracker. What could have introduced a new way for the JDT Content Assist Handler to being aware of content assist requests in ClojureEditors?

**Comment by arichiardi** [comment]
Yes that is the question...maybe some refactoring I did on ClojureSourceViewerConfiguration?

**Comment by arichiardi** [comment]
Maybe [this addition](https://github.com/eclipse/eclipse.jdt.ui/commit/5bf80e2f51330b82217ce9b9a01e470170bf1744#diff-67ad02c03b5742c4873a1d6af91c2396R280)? But I have not checked our code yet...just throwing ideas at you :rabbit:

**Comment by laurentpetit** [comment]
I will close this ticket: I upgrade my Eclipse, and the problem disappeared.

**Comment by arichiardi** [comment]
Oh wow that't good
