### ISSUE TITLE
Enable travis-ci PR builds

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#787]
Pull Request builds could report the status. Probably not deploy, since it could be a dangerous backdoor to CCW public site.

**Comment by arichiardi** [comment]
BTW I wanted to ask you, aren't we targetting 0.33 ?

**Comment by laurentpetit** [comment]
Yes, the milestone name is misleading, renaming it

**Comment by laurentpetit** [comment]
Status Update: Travis CI has 2 infrastructures.
- The old one, which allows the script to use sudo, and install xvfb (virtual X Windows) and Metacity (Window Manager - a Window Manager is a requirement for Eclipse). This allows to start integration tests
- The new one, based on Docker architecture. But there, sudo cannot be used for security reasons. No Window Manager is installed in the Docker containers. So we can't start integration tests on Docker based architecture.

Problem: for each build, there's the need to download hundreds of megabytes from several servers (maven repository, eclipse p2 repositories). This is taking a huge amount of time.

- on the old infrastructure: there's no work-around, and the total build time generally amounts to near 25 minutes.
- on the new docker-based infrastructure, we can activate caching of some directories (for us, it's `${HOME}/.m2/`). This is great.

So we still can't have both at the same time: it's either integration-tests but slow builds, or fast builds and no integration-test.

**Comment by laurentpetit** [comment]
That's why I switched to Jenkins hosted on my own server.

But PRs are still not supported on Jenkins. So we lose this feature (automatic build of PRs). *sigh*

**Comment by arichiardi** [comment]
Yes I saw that Jenkins does not have that, still, yesterday the old guy, together with his good friend maven, was able to catch my oversight...I guess we can leave without it,
I guess you have already checked the [plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin)...I don't see PR management there either..

**Comment by arichiardi** [comment]
At the end of [this](https://developer.github.com/guides/building-a-ci-server/) they say they use [Jenky](https://github.com/github/janky).

**Comment by laurentpetit** [comment]
Didn't say it's not possible with Jenkins. But I won't do it either on my
server, for security reasons. I don't want to spend the time to securely
isolate the build from the server environment, and without that, there's no
way I'll let the server execute arbitrary code coming from PRs from any
github repo in the world.

Le samedi 30 mai 2015, Andrea Richiardi <notifications@github.com> a écrit :

> At the end of this
> <https://developer.github.com/guides/building-a-ci-server/> they say they
> use Jenky <https://github.com/github/janky>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/787#issuecomment-107070190>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ah yes of course there is a big warning on the plugin's page...but there is a PR where they will handle events. We'll keep that under radar.

**Comment by laurentpetit** [comment]
I think it's working
