### ISSUE TITLE
cljc support

### ISSUE THREAD

**Issue by lprefontaine** [laurentpetit/ccw#794]
Hi,
been working a lot with reader conditionals. I added the .cljc everywhere I could find.
Outlines does not seem to recognize this file type as a Clojure one.
Is there a hidden option somewhere that I did not see ?
Or is this embedded in CCW itself ?

Thank you,
Luc

**Comment by laurentpetit** [comment]
It's embedded in ccw (it's in the eclipse plugin.xml file), but yet to be released. Available if you switch to the http://updatesite.ccw-ide.org/branch/master software update site (which will soon be transformed to a release, so very bug free I think)



—
Envoyé avec Mailbox

**Comment by laurentpetit** [comment]
I confirm that it will be part of the release. But thanks for the report, since I helped me notice I hadn't added support for `.cljc` files in the new clojure namespace wizard. This is now fixed.

**Comment by lprefontaine** [comment]
Great :)

I am working on three projects involving reader conditionals.

One involves reworking clara-rules to create a common code base between
Clojure/Clojurescript and since it's Ryan's creation, having an outline 
is kind of necessary. With our internal code it's a bit easier when no outline
can be shown.

That will make things a lot easier.
Thanx
