### ISSUE TITLE
Inconsistent user plugin file structure on github

### ISSUE THREAD

**Issue by asampal** [laurentpetit/ccw#801]
This is just a minor nit, but I noticed that some of the plugin projects include the Eclipse .project file while others don't. It would be more consistent to either include it for all, or not include it for all.

Plugins which don't:
ccw-plugin-ansi-repl
ccw-plugin-repl

**Comment by laurentpetit** [comment]
You're right, there should be consistency. What do you think? Keep or don't keep .project file?
I'm open to suggestions and argumentation in favor of one or the other

**Comment by asampal** [comment]
I'd say to include it since it's created on import anyhow, if it doesn't exist. If you can assume that some people might clone the repos of the plugins that don't include this and then import, modify and push back to a remote in order to submit some changes, it would leave the decision of including/excluding the .project file in a PR up to the respective user. This seems like an arbitrary and unnecessary decision to have to make.

**Comment by laurentpetit** [comment]
Ok, I like this explanation. I will add the missing .project files!



—
Envoyé avec Mailbox

**Comment by laurentpetit** [comment]
ok done
