### ISSUE TITLE
No contents shown in namespace browser when file is loaded

### ISSUE THREAD

**Issue by asampal** [laurentpetit/ccw#804]
I create a new project with the CCW wizard and then try to "Load file in REPL" on the file core.clj that is created. REPL starts and works as expected, but the namespace browser has no contents. On the other hand, if I then open a REPL client on the embedded nrepl server, I can see the namespaces in the browser. As reported, I see issue #800 when double clicking entries. 

eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64
CCW 0.32.0.201507010610

**Comment by laurentpetit** [comment]
I can reproduce the issue. Trying to narrow down to most specific preferences set that creates the problem

**Comment by laurentpetit** [comment]
The issue occurs only when using leiningen to start the repl, and also with cider support.

**Comment by laurentpetit** [comment]
OK, this is fixed in master.

**Comment by asampal** [comment]
This works, but there's still a little glitch. What happens is this:

I do Ctrl+Alt+S and the REPL starts. It doesn't show that the project's namespace was loaded. No project namespace in the browser, only other namespaces. I try to load the file again in the REPL. Now I see, `#'zorba.core/foo` output to the REPL, and now get the proper namespace entry in the browser.

**Comment by laurentpetit** [comment]
Ok, I'll look into this. In the meantime, I have broaden the set of vars
that when double clicked will open the corresponding file in Eclipse (See
#800).

2015-07-03 11:04 GMT+02:00 Adrian Sampaleanu <notifications@github.com>:

> This works, but there's still a little glitch. What happens is this:
>
> I do Ctrl+Alt+S and the REPL starts. It doesn't show that the project's
> namespace was loaded. No project namespace in the browser, only other
> namespaces. I try to load the file again in the REPL. Now I see,
> #'zorba.core/foo output to the REPL, and now get the proper namespace
> entry in the browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/804#issuecomment-118281743>.
>



-- 
Laurent Petit
