### ISSUE TITLE
Bundle error view in standalone CCW

### ISSUE THREAD

**Issue by asampal** [laurentpetit/ccw#805]
It seems this was forgotten.

**Comment by laurentpetit** [comment]
OK, so the answer is we need to include the "org.eclipse.pde" feature to the product.

**Comment by laurentpetit** [comment]
I will do some tests, since including the whole PDE in the standalone product may significantly increase its size, as well as add lots of unnecessary menus entries related to Plugin Development.

**Comment by laurentpetit** [comment]
OK, so the PDE just adds up 20Mb to the standalone product. Will just include it entirely atm.
