### ISSUE TITLE
Assert a min version of CCW for user plugins

### ISSUE THREAD

**Issue by asampal** [laurentpetit/ccw#806]
User plugins should not load if the CCW that's trying to load them doesn't provide the API level they require.

**Comment by laurentpetit** [comment]
The "fix" I implemented is to add an `expect-bundle` fn to `ccw.bundle` namespace.
It can be used like this in a user plugin, at the very top of a script file:

```clojure
(require '[ccw.bundle :as b])
(b/expect-bundle "ccw.core" "0.32.0")

**Comment by asampal** [comment]
What would be the expected version in case you're working with a non-released version of CCW?

**Comment by laurentpetit** [comment]
A non released version of ccw generally is already set to some higher version number with a time stamp qualifier. 

So just incrementing the third number should suffice, I think. 



—
Envoyé avec Mailbox
