### ISSUE TITLE
Clojure 1.7: Go to definition

### ISSUE THREAD

**Issue by casperc** [laurentpetit/ccw#812]
Counterclockwise version: 31.1-STABLE001
Clojure version: 1.7

When running a REPL for a Lein project using Clojure 1.7, the go to definition functionality doesn't work (nothing happens when pressing the F3 key, where in the same project with Clojure 1.6, it goes to the definition).

**Comment by laurentpetit** [comment]
The namespace object no being printed right is the new default with clojure 1.7. But this can maybe be fixed when starting the REPL. Would you please separate this point by creating a proper issue for it?

**Comment by casperc** [comment]
Done. I created a new issue for the printing of namespaces here: https://github.com/laurentpetit/ccw/issues/813

**Comment by laurentpetit** [comment]
Thanks. I tried to reproduce the issue. I can reproduce it with clojure 1.6 set for the project. It's weird that it's working for you with 1.6, but not with 1.7.

**Comment by laurentpetit** [comment]
what are the values of the options for you in the Clojure > General preferences, related to leiningen / cider-nrepl?

**Comment by laurentpetit** [comment]
Oh sorry, I just noticed you report the problem for the stable version. No time to test anymore today, will give it a shot later. Cheers!

**Comment by laurentpetit** [comment]
Ok, so the error is in `ccw.server` code, which relied on the order of `seq` called on a `map`. It should not have done so, since it is an implementation detail that has changed in Clojure 1.7.

I will release a new version of `ccw.server` and use it in Counterclockwise.

**Comment by arichiardi** [comment]
:+1:

**Comment by casperc** [comment]
Just tried the latest build for this (http://updatesite.ccw-ide.org/branch/master/CI0336-master-git47e90ad/) and it seems to have gone wrong somehow or another. Getting this error when opening the executable:

<img width="424" alt="screen shot 2015-07-15 at 20 17 47" src="https://cloud.githubusercontent.com/assets/539481/8706182/9b52e6cc-2b2e-11e5-8139-1d5c7bc323d9.png">

The build before that is fine.

**Comment by laurentpetit** [comment]
Ok, thanks for the report. That's the problem when trying to fix bugs while on holidays, not as professional as usual :-)



—
Envoyé avec Mailbox

**Comment by casperc** [comment]
No worries, take it easy :)

**Comment by laurentpetit** [comment]
So the problem is with the standalone version?
Googling a little bit gives this kind of results: http://stackoverflow.com/questions/7070968/eclipse-executable-launcher-error-unable-to-locate-companion-shared-library

As if this could happen from time to time. It's the first time someone reports the issue to me though.

**Comment by casperc** [comment]
Yes, it is with the standalone version, sorry, I should have said that.

I found those as well and looked at the counterclockwise.ini file to see if anything looked wrong, but everything looked ok to me. It has two paths

-startup
../../plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
--launcher.library
../../plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.200.v20140603-1326

but they both point to stuff that is actually there in the package.

**Comment by laurentpetit** [comment]
currently downloading the version myself (also for OS X), so we'll soon have a double check of the problem ... or not

**Comment by laurentpetit** [comment]
ok, same problem with companion library here. Will relaunch the jenkins build ...

**Comment by casperc** [comment]
Still seeing the problem with the newest build.

**Comment by laurentpetit** [comment]
Gasp



—
Envoyé avec Mailbox

**Comment by laurentpetit** [comment]
ok, so the problem occurs since we switched the version of the standalone product from one of the latest milestones of Mars to the Mars Release ...

**Comment by laurentpetit** [comment]
Upgrading the version of `tycho` (the maven plugin that builds Eclipse projects) from `0.22.0` to `0.23.0` seems to have fixed the issue locally. Pushed to master, and it will hopefully fix the issue there as well.

**Comment by casperc** [comment]
The links for the latest master builds are broken. Looks like the build is having problems uploading the binaries via FTP: https://jenkins.ccw-ide.org/job/ccw-master/344/console

**Comment by casperc** [comment]
On the bright side, I built CCW locally and I can confirm your  your fix has solved both issues (goto definition and the not starting).

Marking as closed.

**Comment by laurentpetit** [comment]
ok, @casperc & @arichiardi , finally got around the issue on the jenkins server. Apparently it was "just" a memory problem. I upgraded the virtual private server hosting jenkins from 1Gb to 2Gb of memory, and now it "seems" that everthing's back again. This will be confirmed tomorrow when the current build is finished

**Comment by arichiardi** [comment]
:+1:
