### ISSUE TITLE
Clojure 1.7: REPL printing

### ISSUE THREAD

**Issue by casperc** [laurentpetit/ccw#813]
The namespace object is not printed right when using "Switch REPL to file's namespace" when using Clojure 1.7. It is printed as 

#object[clojure.lang.Namespace 0x23dbd676 "microservice.core"]

Edit: Same goes when deffing a var in the REPL:

`(def something [1 2 3 4])`
prints 
`#<Var@6957c8f3: [1 2 3 4]>`

`(defn somefn [] (prn "something"))`
prints
`#<Var@415b78a2: #object[microservice.cassandra$somefn 0x222b9f0e "microservice.cassandra$somefn@222b9f0e"]>`

**Comment by laurentpetit** [comment]
This has indeed to be improved. We need to detect the clojure version, and when 1.7 or higher, set the right dynamic var for both the printing of objects and the error reporting so it's reported as before.

**Comment by arichiardi** [comment]
Yes Clojure 1.7 has changed some things about printing exceptions and objs in general. There has been some fuss around it :)

**Comment by arichiardi** [comment]
The problem is not as easy at it seems... [Here](https://github.com/clojure/clojure/blob/master/changes.md#27-printing-as-data) some info.

**Comment by arichiardi** [comment]
Maybe we can just specify a ```print-method``` for ```Namespace``` if >1.7...or drop printing the namespace...I guess we don't need/want to change too much at the REPL...

**Comment by laurentpetit** [comment]
Yes we can probably check if there's a print-method for namespaces, and if not, add one. Chad published the code on Twitter / github snippets.

**Comment by arichiardi** [comment]
Harrington? I checked but could not find it...

**Comment by arichiardi** [comment]
Ok, I wrote, very easily my own...now I just need to find where/how to put it:

```clojure
(defmethod print-method clojure.lang.Namespace [v ^java.io.Writer w]
  (.write w (str v)))
```

Basically I hope there was a method to execute it just when ```ccw``` switches but not for everything. For instance, let's say somebody uses ```*ns*```, that should print according to ```clojure```'s printing (tagged object in 1.7...).

**Comment by arichiardi** [comment]
Found! fixing as we speak,

**Comment by arichiardi** [comment]
Nope, the problem is that every execution prints out something, therefore I cannot do:
```clojure
(defmethod...)
(in-ns ...)
(remove-method)
```

Maybe there is a way to avoid printing the result of an evaluation?

**Comment by laurentpetit** [comment]
I don't understand, sorry 



—
Envoyé avec Mailbox

**Comment by arichiardi** [comment]
No problem, basically on namespace switching I can execute

```clojure
(defmethod...)       ;; sets the new print-method
(in-ns ...)               ;; performs the namespace change 
(remove-method)  ;; removes the multi method so that we don't interfere with the user repl session
```

The problem is that each evaluation prints a result, that in case of the multi method addition/removal is not what we wanted. If there were a way to mute the evaluation result just for some instruction...I would have solved.

I am browsing the code base to see if it is feasible, and I suggestions are more than welcome :smile:

**Comment by arichiardi** [comment]
BTW I have found [gist](https://gist.github.com/cemerick/c8ed5730b0055f41cbef) but I think my problem persist, and my solution less invasive for the user.

**Comment by laurentpetit** [comment]
Don't we control the final printing to the log area of the repl view? Maybe
we could just check the content with a regex like
#"object\[clojure.lang.Namespace[^\"]+\"([\"]+)\"\]" and if it matches then
replace it with the matched group?

I'm a little bit concerned about creating then removing a print-method on
every evaluation. It's not thread safe.

Another option would be to install once and for all a print method for the
namespace, which would either delegate to the print-object method, or own
repl-custom print code.
The choice would be driven by a new dyn bar we would also introduce once
and for all in clojure.core. We could then thread-safely bond this var
during evaluation of user code sent via the REPLView.

Le samedi 18 juillet 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> BTW I have found gist
> <https://gist.github.com/cemerick/c8ed5730b0055f41cbef> but I think my
> problem persist, and my solution less invasive for the user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/813#issuecomment-122587425>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
I did not know that ```defmethod``` is not thread safe, thanks!
Maybe the first option is easier to implement...

**Comment by laurentpetit** [comment]
No it's not the fact that defmethod is not thread safe (which is also right indeed as far as I know), but the fact that it's a global change that will be visible by any thread while the repl expression is evaluating. 



—
Envoyé avec Mailbox

**Comment by arichiardi** [comment]
Well, that particular nrepl instance will evaluate the three instructions in sequence and the problem might be that, if someone else evaluates between ```defmethod``` and ```in-ns```, she will see a different printing of ```Namespace```. Am I completely on the wrong path?
In any case filtering the output of the evaluation feels cleaner...

**Comment by laurentpetit** [comment]
Yes. That's it. 

Filtering the output could be something proposed as a post processing that can be overrides by user plugins, by the way. 



—
Envoyé avec Mailbox

**Comment by casperc** [comment]
I updated the top post with two more examples of things that are not printed correctly: def and defn

**Comment by arichiardi** [comment]
As said, we cannot change the behavior of ```clojure.core```, only workaround the commands that are "ccw's", like the namespace. If you want to change all the printing to 1.6, follow this [gist](https://gist.github.com/cemerick/c8ed5730b0055f41cbef).
I will provide a way to override the display through user plugin, but it is an advanced feature that not everybody would want to have.

**Comment by arichiardi** [comment]
I am working on this, taking the time for the tests as well.

**Comment by laurentpetit** [comment]
I'm making my mind on this issue as well

**Comment by laurentpetit** [comment]
Well, maybe the current `cider-nrepl` version is tricking us, at least for the `def` `defn` parts. Seems like it tried to stick to ClojureScript way of printing, rather than Clojure? Will do some tests without `cider-nrepl` enabled.

**Comment by laurentpetit** [comment]
OK, so as far as `defn` and `def` are concerned, it seems like it's an issue with `cider-nrepl`'s `pprint` middleware, which is now active by default.
I contacted the cider team.
For the *ns*, the initial mentioned problem remains.
I think we should split this issue in two.

**Comment by laurentpetit** [comment]
WRT pprint: I posted the problem with pprint to the clojure-dev ml: https://groups.google.com/d/msg/clojure-dev/pUG0cDkyK_s/Rsnb4_HGyQwJ

**Comment by laurentpetit** [comment]
@casperc in order not to see the wrong display for `defs`, the workaround is to disable the usage of `pprint` in the Clojure > REPL View preferences. The issue exists since at least Clojure 1.6, and lies within `clojure.pprint/pprint`.

**Comment by laurentpetit** [comment]
Ok, so for the issue with pprinted vars, I have "backported" the solution from clojure 1.8.0-alpha2 dynamically.

For the initial problem, *ns* not displayed correctly (as well as *e), there's no clean solution without patching nrepl heavily (replacing interruptible-eval middleware).
So I will apply the not-so-clean solution of reverting back to 1.6.0 `print-object` for the whole process JVM.

**Comment by laurentpetit** [comment]
Maybe I'll add a preference to revert back to this behavior, set to true by default.

**Comment by arichiardi** [comment]
Yes i was goint to suggest a preference

**Comment by laurentpetit** [comment]
Done. Both problems are solved.One with a hack which will stay for at least as long as some people use clojure 1.7 or below (for pprint). the other which is enabled by default, but has a preference for disabling it (*ns* and *e printing).
