### ISSUE TITLE
Auto completion works wrong for built-in Clojure symbols

### ISSUE THREAD

**Issue by noncom** [laurentpetit/ccw#823]
When typing in a built-in Clojure symbol like `do` or `let` or any other, the Eclipse auto completion tends to hinder the input, favoring user-defined symbols.

For example, I have a symbol `parse-adb-log` in the  namespace and I want to create a `(do ...)` form somewhere. So I type in `do` and Eclipse proposes to complete with `parse-adb-log`. If I naturally hit `ENTER` after typing in `do`, it substitues my intended input with `parse-adb-log`.

There is no way to make it settle down with `do` without dismissing the auto complete prompt first. And that takes an additional action like a mouse click, a cursor key hit or an `ESC` key hit. The little issue can become rather annoying over time..

**Comment by laurentpetit** [comment]
Indeed. I'll add the built-in symbols to the list.This should do the trick.
