### ISSUE TITLE
Losing colors in editor

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#824]
recent regression

**Comment by arichiardi** [comment]
I found out that in my case the .clj file was not opened with Clojure stuff but with the ```Default``` editor, which I don't think actually is a ```ClojureEditor```.

**Comment by laurentpetit** [comment]
I'll check that. It remains weird that both of us had the same symptom at the same time ..

**Comment by laurentpetit** [comment]
Does not seem to happen again on my laptop either. Closing it.
