### ISSUE TITLE
Wrong version of ANSI plugin in CCW 0.32.0-STABLE

### ISSUE THREAD

**Issue by smee** [laurentpetit/ccw#829]
I get the following error message in the log:
```
!MESSAGE Exception loading User Script D:\tools\counterclockwise-0.30.0.STABLE001\plugins\ccw.core_0.32.0.STABLE001\ccw-plugins\ccw-plugin-ansi-repl\ansi-repl.clj
!STACK 0
java.lang.RuntimeException: No such var: view-helpers/ui-async, compiling:(D:\tools\counterclockwise-0.30.0.STABLE001\plugins\ccw.core_0.32.0.STABLE001\ccw-plugins\ccw-plugin-ansi-repl\ansi-repl.clj:92:7)
```
If I replace the contents of ```ccw-plugins/ccw-plugin-ansi-repl/ansi-repl.clj``` with the version of https://github.com/ccw-ide/ccw-plugin-ansi-repl/commit/58ba27cfa8a7d8d228cc75f13c18751aa57d983a everything works as advertised.

**Comment by laurentpetit** [comment]
Argh, I got caught by Git submodules, it seems. The jenkins builder may not
have correctly updated its submodules at the start of the build.

2015-07-30 11:56 GMT+02:00 Steffen Dienst <notifications@github.com>:

> I get the following error message in the log:
>
> !MESSAGE Exception loading User Script D:\tools\counterclockwise-0.30.0.STABLE001\plugins\ccw.core_0.32.0.STABLE001\ccw-plugins\ccw-plugin-ansi-repl\ansi-repl.clj
> !STACK 0
> java.lang.RuntimeException: No such var: view-helpers/ui-async, compiling:(D:\tools\counterclockwise-0.30.0.STABLE001\plugins\ccw.core_0.32.0.STABLE001\ccw-plugins\ccw-plugin-ansi-repl\ansi-repl.clj:92:7)
>
> If I replace the contents of
> ccw-plugins/ccw-plugin-ansi-repl/ansi-repl.clj with the version of
> ccw-ide/ccw-plugin-ansi-repl@58ba27c
> <https://github.com/ccw-ide/ccw-plugin-ansi-repl/commit/58ba27cfa8a7d8d228cc75f13c18751aa57d983a>
> everything works as advertised.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/829>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
Currently building 0.32.0 again, changing the qualifier from 0.32.0.STABLE001 to 0.32.0.STABLE002.
