### ISSUE TITLE
Load file in REPL only starts the REPL and does not load the file

### ISSUE THREAD

**Issue by noncom** [laurentpetit/ccw#833]
I've updated to Eclipse Mars + CCW 0.32.0.STABLE002 and on "load file in repl", if I have no current repl running, CCW just starts a repl, without loading the file into it and switching to the namespace.

**Comment by laurentpetit** [comment]
Should be available in software update site http://updatesite.ccw-ide.org/branch/master in 1/2 hour if jenkins doesn't detect any regression.
