### ISSUE TITLE
can't type @ on german keyboard layout

### ISSUE THREAD

**Issue by talvdav** [laurentpetit/ccw#841]
Altgr+Q dose nothing in every Editor or Repl.
Only works in prefrence menu

**Comment by laurentpetit** [comment]
It's probably the binding introduced by the command "show active REPL".
I will disable this binding by default.
In the mean time, you can do it yourself via `Preferences > General > Keys > type filter 'active repl` ; in the `Binding` form entry, remove the binding. Save. You're done.

**Comment by talvdav** [comment]
Hi Lauren,

thank you for the quick response!

Quick note:
Restart Eclipse after removing the keybinding.
