### ISSUE TITLE
False detection of a hyperlink in a String literal

### ISSUE THREAD

**Issue by noncom** [laurentpetit/ccw#847]
I just came across a case where a hyperlink is incorrectly detected in a String literal.

The literal:

`(println "========================================================================== debug :")`

Various stages of the issue:
* http://joxi.ru/eAOqL9eSO4lJmo - the literal with unprintable characters
* http://joxi.ru/gmvR8BYFlxE4ma - the highlight and proposed options
* http://joxi.ru/n2Y8e9dFJjQLm6 - the result of clicking on an option

**Comment by laurentpetit** [comment]
Which OS do you use? I cannot reproduce this issue on my OS X.

**Comment by noncom** [comment]
Probably a Windows-specific problem with paths. The `java-resource-paths` strategy was failing when it appended the "path" taken from the string literal to the projects `root-path` where `org.eclipse.core.runtime.Path` was silently dropping the appendage off because it containted the illegal `:` character, and was effectively returning the `root-path` as the target for the incorrectly-assumed hyperlink in the String literal.

Per out talk, the PR applies a patch that prevents `java-resource-paths` strategy from considering folders as valid targets.
