### ISSUE TITLE
Create a remote REPL

### ISSUE THREAD

**Issue by mikera** [laurentpetit/ccw#857]
It would be great if we could open CCW REPLs for remote processes (or other local processes, e.g. a figwheel instance)

Is this possible already? If not could it be considered as an enhancement?

**Comment by laurentpetit** [comment]
Hello,

It is already possible, the menu entry is in the Window top menu. 
Cheers,

Laurent

**Comment by mikera** [comment]
Ah I see it now. Thanks!
