### ISSUE TITLE
Code completion freezes Eclipse

### ISSUE THREAD

**Issue by royaldark** [laurentpetit/ccw#858]
I just upgraded to the newest (0.34.0.STABLE001), and the code completion seems much worse than before. When I begin typing a namespace name, the completion now locks Eclipse for about 5 seconds. To add insult to injury, completions that used to work fine no longer do - it seems I now need to type significantly more of the namespace name before the right completions appear.

Did code completion change in a recent version? Are there any configuration settings I can change to help fix the 5-second freeze issue?

**Comment by laurentpetit** [comment]
Hello Joe,

Please try to turn off the Cider Nrepl support:
http://doc.ccw-ide.org/documentation.html#_cider_nrepl_support to go back
to ccw's own library. My bet is that it's the culprit.

2015-12-04 21:25 GMT+01:00 Joe Einertson <notifications@github.com>:

> I just upgraded to the newest (0.34.0.STABLE001), and the code completion
> seems much worse than before. When I begin typing a namespace name, the
> completion now locks Eclipse for about 5 seconds. To add insult to injury,
> completions that used to work fine no longer do - it seems I now need to
> type significantly more of the namespace name before the right completions
> appear.
>
> Did code completion change in a recent version? Are there any
> configuration settings I can change to help fix the 5-second freeze issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/858>.
>



-- 
Laurent Petit

**Comment by royaldark** [comment]
Turning off cider-nrepl support worked like a charm! Thanks!
