### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by PhilipMay** [laurentpetit/ccw#868]
Hello,
I just saw that this project has not been active this year.
Is it still being developed? Just asking because I do not want to
use "dead" software projects for my development.
Thanks.

**Comment by arichiardi** [comment]
I am not the maintainer and I do not want to start a flame, but as a note, IMHO this is not the right way to ask this in open source projects.

Open source is maintained out of people's "generosity" and ability to contribute freely to the community. Probably mainteners are super busy now and cannot do better.

A better approach would be to maybe review some PR/contribute yourself/fork, if you can. I read once an article about the fact that open source users tend to consider themselves customers. Well, yes and no.

Just food for thought here, apologising in advance if it's not the answer to your question.

**Comment by laurentpetit** [comment]
Hello,

I'm the main sponsor of the project. 
All the activity around the project is done in public. 
So you can judge by yourself. 

You would have more interesting answers by asking questions on the mailing list, I guess.
